<?php

$products = array(
    array(
        'product_main_image' => 'https://media.istockphoto.com/photos/orange-men-shorts-for-swimming-picture-id697913308?k=6&m=697913308&s=612x612&w=0&h=zdbaLlgRJRUX92dbnoPDTdHlDNpBa1jsnsofIOoQt94=',
        'product_gallery' => array(
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8mmtnqllD0JHde_iNMtT2J5sL2I41qbAmVD5QT4XZRAUlQl5i6J4aIsbZvhjrVKyRaps&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWpFSi9bL2yb-XyqDV9PfudNh4cChVHsb0WvihToU_l-jkoHaP3JyX4kmlqjj43YU6elo&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSl1jVBfH3pzs9Y6bxIFcF9e1A-Xss0Ew9H1RgLNrCIy6eIZMa-ZRZtDSQcGZ8ihrYEUy4&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr_Wbj8m_QwITtyypRVgnOF9p0LuUPK1I6lP6i0rIj0JZ1gPuYih2QUizrH4n2Zc1Qvck&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR120cCb-mfsytGMGOOgJGNyTuqH9AwIShQEziFimuwH3aOKVXdpvvevV_1u-IYL40KrkE&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwnp4gEO4zy3ooNQmpfCTsuzz95gIhr4M0Cwi-4TTX_tjFN2CVxtmZh5pO5AcT9SPecAI&usqp=CAU'),
        'product_title' => 'Orange Shorts',
        'product_description' => 'Orange shorts for man',
        'product_price' => 50,
        'product_sale_price' => 45,
        'product_on_sale' => 1,
        'product_youtube' => 'https://youtu.be/mILth-K6KvM',
    ),
    array(
        'product_main_image' => 'https://cdn.shopify.com/s/files/1/0931/4836/products/40414620-zoom_b892a32f-4216-4f52-a874-9c1b33ab1d37.jpg?v=1494767722',
        'product_gallery' => array(
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGShU1gWKDYqGGg3dMr1qqs15Fb_6bVqE3ODxAe0sHLed_csYF4L5EkU-SL980q3kGi4U&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk2RODo0YtV_A5m8KcNGh9Ve-OoABnebkrGkxRZ30orMtygaZKbTWYQlJoX9CMCOeoyA8&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1No2YR4d818xKo97nU6efkIYks0YxY-PjCpkFsRxkeWbmvWAQ5MPyKsXSq0UqlqkO9FU&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz5DrZFpsIdt8RX3rIRZBkr_oE2pajtNms2fJSYaiUX-F9tBGP_-CUhylFfK13aATn5cI&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDxcFvxEpUc_NAZwTx7f2Z0gXZgFio6yMPK3zJgaX-IZclTyV1GiVDmjL-uTGrgY7bOHI&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRf6PYXOV7SC5QysPiIJGO6xoW0zJe57l-crFi2n4Mhskjh9TeLB0wfenyhCoMBRxaePK4&usqp=CAU'),
        'product_title' => 'Blue Shorts',
        'product_description' => 'Blue shorts for man',
        'product_price' => 60,
        'product_sale_price' => 48,
        'product_on_sale' => false,
        'product_youtube' => 'https://youtu.be/mILth-K6KvM',
    ),
    array(
        'product_main_image' => 'https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F02%2F01%2F0201b56b44cb906ddf48f0c56c8ca71052f902a1.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5Bmen_shorts%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]',
        'product_gallery' => array(
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSSjRN3mRHrZVSxtJOBx4gacHmzdBYzJqOchyNNPXff6QSRtcXLEKtVfeU_cEPLlrnuQo&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLgUrnkWjjLGocosMPN5S06wttmMNgwIWYw5QUTOvkmTx_8bLhJEaI2d4WdvoxJRGtp6Y&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTS1yLh3ZFu1SURhYLLepdyhy-Xh2TG8jvtWrXNSgmZ6NuN0bazhRpN_FZszvcbA101Kho&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2vFIq1-97EYrbqp7ciXdXvjxq-YuyDwr2cGKW2gJxkyS1tOkJQU8eQc8CE-dT3xPCF5U&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsjJ_CLwlRoJuG1DVflWFCuJ3nSv-Q6yDUEtN1slUSQHYf2BIyuT7XFOUDLAO71ln4DZ4&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2NN-jr_yaPONkQLYVm81HXeEWcGky2Q-4peD5-_u6k5EEd9_IRP58Vo1dEzhz0jup2CA&usqp=CAU'),
        'product_title' => 'Black Shorts',
        'product_description' => 'Black shorts for man',
        'product_price' => 30,
        'product_sale_price' => 20,
        'product_on_sale' => 1,
        'product_youtube' => 'https://youtu.be/mILth-K6KvM',
    ),
    array(
        'product_main_image' => 'https://il.theshirtcompany.com/media/catalog/product/cache/b8ddf67ecffad361da07a2b9679d789e/m/a/madelena_2.jpg',
        'product_gallery' => array(
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmUAV5l2zp-hNDKN2Cb-55mamhVX28fYLKXVVUQVF2BNtY2F6e8Vnh66ijpQzJDDuLGm0&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWFLaRVJsByG6v4hTwjL9z0EqJ5xlihraBBsiaoo16X_vtsa1K-GVEb_lJTZXlwUMqF7k&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp5WrVwZ65VNWsYUpsoEBpTqx14zG0QvkLEINlHcF8xflBXtBr7dKJ1te6D48qYDVLSz0&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqAmx98oqcVPoHVoOTVGe4-O8Dy4NglcChIA4AoSiiFr15ndXNfoP5PHFCvVMs2mtuOsY&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYFdZctyVEWm7FcdIUehHcTXHxTCzWz4IWvVQKnAQ1EqsI-zyf3yPHXnBz_qDuUo9YK94&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjCSqWY7qSMaocfRFo-_MWTkADgbF_-6iGi-1Zp5pdIpewxTxcB9j_yetJKMgVOx12Trw&usqp=CAU'),
        'product_title' => 'White Shirt',
        'product_description' => 'White shirt for woman',
        'product_price' => 90,
        'product_sale_price' => 67,
        'product_on_sale' => 1,
        'product_youtube' => 'https://youtu.be/mILth-K6KvM',
    ),
    array(
        'product_main_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlSro6nuVZL1s9wkgVXuuEwnsqyxbNGekLyA&usqp=CAU',
        'product_gallery' => array(
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLcyCxucMyISEnlQ9TPJwDeG9R7j8X7vPVVOnzUMIDFsVOduvXWMNax4k7tM77NualZeY&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3nk7EAK7MVuVg7Y4lMj0-HfCJkicXDCZ-_xzxqorywwF3dpaIRoyNpmzas1y-GD4fSUQ&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk-YsGusDyOLQfUvIkNOAaMYYJPzUkMF5LA57-suib4aRW8PUaL4usDE_m9T-3yjA30r4&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMXi05uWFet9vS3PTN4UHe-4wy4xtoWzKcdzw8IumG8uAxodY8SiCWgtyU0VBOz5w3VDU&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQteS3ZBvHHkMLrqhTzVlNYwt2icQyQzAigQCbv0R8IbuPUE4e2ZhELXt9T5MnmQ1LJr1k&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_8mCyS-z1p5RgU_hHzzAqWHH1R2trshUzeLGoPsO2F_OODq9799gIKwPZmZjKXvvZ2xE&usqp=CAU'),
        'product_title' => 'Red Shirt',
        'product_description' => 'Red shirt for woman',
        'product_price' => 52,
        'product_sale_price' => 43,
        'product_on_sale' => false,
        'product_youtube' => 'https://youtu.be/mILth-K6KvM',
    ),
    array(
        'product_main_image' => 'https://img.withoutgraphics.eu/prod/max/172/royal-blue-womens-t-shirt-organic-cotton-23376.jpg',
        'product_gallery' => array(
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdcWsAy_C0S7cB5Jir7dVE5lAMk0F34z-hqbJiRa-i7yOccc7f6CILNQEP_qz5MejQynw&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9AmRDLCQ4s0SlJnHPTCarRD-a9PBcqFIpBXPyoKNCegxc2VPxu0uC6GEp-iLGytHsiMM&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8RkqIOM4Pk0NX_3g2ENkuIH_OpQ62QVK4IcpoKSmmpkKtDd33T281VswQ3UOCvotpEGY&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB3raDawKjyq_hEfGmXdDIwrnUWeE9vKDFG9URbCWTqBQDaCoYoSJzWg2doyRBUbztYWk&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl95eIbshYuVT19BbyMwF2RzXGaE44_psotqHgrpKR4nLw3Ls94p4RpmxeSGZfmEpJPLI&usqp=CAU',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxQIe4A92irjT6nnRZlzHz8zGGbqgUMzRVdTvFZcQYU5xm852MVARcJCyXUvkG_StClCs&usqp=CAU'),
        'product_title' => 'Blue Shirt',
        'product_description' => 'Blue shirt for woman',
        'product_price' => 58,
        'product_sale_price' => 49,
        'product_on_sale' => false,
        'product_youtube' => 'https://youtu.be/mILth-K6KvM',
    ),
);

return $products;